name: tms_risk
channels:
  - conda-forge
dependencies:
  - python
  - pymc=5.17
  - compilers
  - arviz=0.20
  - notebook
  - seaborn
  - pandas
  - numpy=1.25
  - scipy
  - nilearn
  - tqdm
  - pip  # ensure pip is installed in the environment
  - tensorflow
  - tensorflow-probability
  - pip
  - pip:
      - -e .
      - ./libs/braincoder  # Path to the braincoder submodule
      - ./libs/bauer       # Path to the bauer submodule (if added)
