name: tms_risk
channels:
  - conda-forge
dependencies:
  - python
  - pymc=5.17
  - compilers
  - arviz=0.20
  - notebook
  - seaborn
  - pandas
  - numpy=1.25
  - scipy
  - nilearn
  - tqdm
  - mkl           # Ensure MKL is included
  - mkl-include   # Optional, includes development headers for MKL
  - pip
  - tensorflow
  - tensorflow-probability
  - pip
  - pip:
      - -e .
      - ./libs/braincoder
      - ./libs/bauer
