"""Model comparison on the ORDER ASYMMETRY, not on ELPD.

The cTBS signature the paper is about is qualitative and specific: P(chose risky)
rises under IPS stimulation when the risky option is presented SECOND, and not when
it is presented first. ELPD scores a model on all 8,335 trials at once, so a model
can win it while reproducing none of that asymmetry -- which is what happens here.

Score per model: asymmetry = mean_stakes DeltaP(risky second) - mean_stakes DeltaP(risky
first), for the posterior-predictive median and for the data. Reads the
`ppc_delta_by_stake.*.tsv` written at fit time (so each model's PPC was generated by
the bauer that produced its trace), plus `notes/data/ploo/*.npz` for ELPD.

Caveat carried on the figure: the asymmetry is computed from each cell's posterior
MEDIAN, because the stored PPC tables keep only median/lo/hi per cell, not draws. It
is therefore a point summary with no interval -- fine for ranking models, not for a
claim about any one of them.

    python -m tms_risk.behavior.scripts.plot_order_effect_comparison
"""
import argparse
import glob
import json
import re
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

mpl.rcParams.update({
    'font.family': 'Helvetica',
    'font.sans-serif': ['Helvetica', 'Helvetica Neue', 'TeX Gyre Heros', 'Arial'],
    'font.size': 7, 'axes.labelsize': 8, 'axes.titlesize': 8,
    'xtick.labelsize': 7, 'ytick.labelsize': 7,
    'axes.linewidth': 0.8, 'axes.spines.top': False, 'axes.spines.right': False,
    'xtick.direction': 'out', 'ytick.direction': 'out',
    'xtick.major.size': 3, 'ytick.major.size': 3,
    'lines.linewidth': 1.2, 'legend.frameon': False,
    'pdf.fonttype': 42, 'ps.fonttype': 42, 'svg.fonttype': 'none',
    'figure.dpi': 150, 'savefig.dpi': 300,
})

C_FLEX = '#3B5BA5'     # magnitude-dependent (flexible) noise
C_WEBER = '#D8801F'    # scalar (Weber) noise
C_NULL = '#9C9C9C'     # no cTBS effect
C_PRIOR = '#5D8C3F'    # cTBS on the PRIOR (preferences) rather than on noise

NAMES = {
    'lfx2-bs3-w-dp-bm':     ('Log-Weber, cTBS both channels', C_WEBER),
    'lfx2-bs3-w-dp-b':      ('Log-Weber, cTBS perceptual', C_WEBER),
    'lfx2-bs3-w-dp-null':   ('Log-Weber, no cTBS', C_NULL),
    'lfx2-bs3-m2-dp-bm':    ('Log-Flexible, cTBS both (PRIMARY)', C_FLEX),
    'lfx2-bs3-m2-dp-b':     ('Log-Flexible, cTBS perceptual', C_FLEX),
    'lfx2-bs3-m2-dp-null':  ('Log-Flexible, no cTBS', C_NULL),
    'lfx2-bs2-m3-dp-bm':    ('Log-Flexible, alt. basis', C_FLEX),
    'lfx2-bs3-m3-dp-bm-fs': ('Log-Flexible, pinned prior SDs', C_FLEX),
    'lfx2-bs3-m3-dp-bm-op': ('Log-Flexible, objective prior', C_FLEX),
    # The preference account: cTBS shifts the magnitude PRIOR, not the noise.
    # Ties the noise model on ELPD (-4182.6 vs -4184.6, z = -0.2) and so cannot
    # be ruled out that way -- but reproduces almost none of the order asymmetry.
    'flexible1_noisefix_prior': ('cTBS on PRIOR (preferences)', C_PRIOR),
}


def score(f):
    lab = re.sub(r'.*ppc_delta_by_stake\.|\.tsv', '', f)
    d = pd.read_csv(f, sep='\t')
    if not {'order', 'obs', 'median'} <= set(d.columns):
        return None
    snd, fst = d[d.order == 'Risky second'], d[d.order == 'Risky first']
    return dict(
        label=lab,
        mod_asym=snd['median'].mean() - fst['median'].mean(),
        obs_asym=snd['obs'].mean() - fst['obs'].mean(),
        mod_second=snd['median'].mean(), obs_second=snd['obs'].mean(),
        band=float((d.hi - d.lo).mean()),
    )


def elpds(ploo_dir):
    out = {}
    for p in glob.glob(str(Path(ploo_dir) / '*.npz')):
        z = np.load(p)
        m = json.loads(str(z['meta']))
        out[m['label']] = z['elpd_i'].sum()
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--data_dir', default='notes/data')
    ap.add_argument('--out', default='notes/figures/order_effect_comparison')
    args = ap.parse_args()

    rows = [r for r in (score(f) for f in
                        sorted(glob.glob(f'{args.data_dir}/ppc_delta_by_stake.*.tsv')))
            if r and r['label'] in NAMES]
    t = pd.DataFrame(rows)
    t['name'] = t.label.map(lambda l: NAMES[l][0])
    t['color'] = t.label.map(lambda l: NAMES[l][1])
    E = elpds(f'{args.data_dir}/ploo')
    t['elpd'] = t.label.map(E)
    t = t.sort_values('mod_asym')
    obs = float(t.obs_asym.iloc[0])

    fig, axes = plt.subplots(1, 2, figsize=(7.25, 2.9), constrained_layout=True,
                             gridspec_kw=dict(width_ratios=[1.5, 1]))

    # -- a: how much of the observed asymmetry each model reproduces ---------
    ax = axes[0]
    y = np.arange(len(t))
    ax.barh(y, t.mod_asym, color=t.color, height=.66, alpha=.9, lw=0)
    ax.axvline(obs, color='.15', lw=1.1, ls='--', zorder=3)
    ax.text(obs, len(t) - .35, f'Observed\n{obs:.3f}', fontsize=6.5, ha='right',
            va='top', color='.15', linespacing=1.3)
    for yi, r in zip(y, t.itertuples()):
        ax.text(r.mod_asym + .0009, yi, f'{100 * r.mod_asym / obs:.0f}%',
                va='center', ha='left', fontsize=6.3, color='.35')
    ax.set_yticks(y)
    ax.set_yticklabels(t.name, fontsize=6.5)
    ax.tick_params(axis='y', length=0)
    ax.set_xlim(0, obs * 1.14)
    ax.set_xlabel('Order asymmetry, ΔP(chose risky)\nrisky-second − risky-first')
    ax.set_ylim(-.7, len(t) - .3)

    # -- b: ELPD does not track the qualitative signature -------------------
    ax = axes[1]
    for r in t.itertuples():
        if not np.isfinite(r.elpd):
            continue
        ax.plot(r.elpd, r.mod_asym, 'o', ms=6, mfc=r.color, mec='white', mew=.7,
                zorder=3)
    ax.axhline(obs, color='.15', lw=1.1, ls='--', zorder=0)
    ax.text(.02, obs, 'Observed', fontsize=6.5, va='bottom', ha='left',
            color='.15', transform=ax.get_yaxis_transform())
    best = t.loc[t.elpd.idxmax()] if t.elpd.notna().any() else None
    if best is not None:
        ax.annotate('Best ELPD', xy=(best.elpd, best.mod_asym),
                    xytext=(best.elpd - 40, best.mod_asym + .013),
                    fontsize=6.5, color='.25', ha='left', va='center',
                    arrowprops=dict(arrowstyle='-|>', color='.25', lw=1.0,
                                    mutation_scale=8, shrinkA=3, shrinkB=7,
                                    relpos=(1.0, 0.5),
                                    connectionstyle='angle3,angleA=0,angleB=-60'))
    ax.set_xlabel('ELPD (nats)')
    ax.set_ylabel('Order asymmetry (model)')
    ax.set_ylim(-.004, obs * 1.15)

    sns.despine(fig=fig, offset=4)
    for ax, letter in zip(axes, 'ab'):
        ax.text(-0.06, 1.06, letter, transform=ax.transAxes, fontsize=8,
                family='Arial', fontweight='bold', va='bottom', ha='right')

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    for ext in ('pdf', 'png'):
        fig.savefig(f'{args.out}.{ext}', bbox_inches='tight', pad_inches=0.02)
    t.to_csv(f'{args.out}.tsv', sep='\t', index=False)
    print(t[['label', 'mod_asym', 'elpd']].to_string(index=False))
    print(f'\nobserved asymmetry {obs:.4f}; best model reproduces '
          f'{100 * t.mod_asym.max() / obs:.0f}%')
    print(f'wrote {args.out}.pdf / .tsv')


if __name__ == '__main__':
    main()
